spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/heartfolio?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1015
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
server:
  port: 8080