name: CI/CD

on:
  push:
    branches:
      - dev

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      # SOURCE 단계 - 저장소 Checkout 및 서브모듈 가져오기
      - name: Checkout-source code
        uses: actions/checkout@v3
        with:
          submodules: true  # 서브모듈도 가져옵니다

      # 서브모듈의 파일을 resources 디렉토리에 복사
      - name: Copy submodule files to resources
        run: cp -r secrets/develop/* src/main/resources/

      # Gradle 실행권한 부여
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Spring boot application 빌드
      - name: Build with gradle
        run: ./gradlew clean build

      # docker image 빌드
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/heartfolio_b:0.0.1 .

      # docker hub 로그인
      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # docker hub 퍼블리시
      - name: Publish to docker hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/heartfolio_b:0.0.1

      # WAS 인스턴스 접속 & 애플리케이션 실행
      - name: Connect to WAS & Execute Application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ${{ secrets.WAS_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.WAS_SSH_PORT }}
          script: |
            docker stop backend
            docker rm backend
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/heartfolio_b:0.0.1
            docker run -d -p 8080:8080 --name backend ${{ secrets.DOCKERHUB_USERNAME }}/heartfolio_b:0.0.1
