name: CI/CD

on:
  push:
    branches:
      - dev

jobs:
  backend-deploy:
    runs-on: self-hosted
    steps:
      # SOURCE 단계 - 저장소 Checkout 및 서브모듈 가져오기
      - name: Checkout-source code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
          submodules: true  # 서브모듈도 가져옵니다
          fetch-depth: 0        # 모든 커밋을 가져옵니다.
          submodule-update-strategy: checkout # 서브모듈을 최신 커밋으로 업데이트

      # 서브모듈의 파일을 resources 디렉토리에 복사
      - name: Copy submodule files to resources
        run: cp -r secrets/* src/main/resources/

      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Gradle 실행권한 부여
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Spring boot application 빌드
      - name: Build with gradle
        run: ./gradlew clean build

      # docker image 빌드
      - name: Build docker image
        run: docker build -t limzzum/heartfolio_b:0.0.1 . --no-cache

      # docker hub 로그인
      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # docker hub 퍼블리시
      - name: Publish to docker hub
        run: docker push limzzum/heartfolio_b:0.0.1

      # 애플리케이션 실행
      - name: Execute Application
        run: |
            docker stop backend
            docker rm backend
            docker pull limzzum/heartfolio_b:0.0.1
            docker run -d -p 8080:8080 --name backend limzzum/heartfolio_b:0.0.1
            docker image prune -f
